### ISSUE TITLE
Should the key be `typ` or `type`?

### ISSUE THREAD

**Issue by celie56** [Jayy001/Carta#6]
`typ` is mentioned in 
* https://github.com/Jayy001/Carta/blob/6a9b9692ff180ca481555e2f3e8708c947cdc095/README.md?plain=1#L45
* https://github.com/Jayy001/Carta/blob/6a9b9692ff180ca481555e2f3e8708c947cdc095/README.md?plain=1#L78

but `type` is used in
* https://github.com/Jayy001/Carta/blob/6a9b9692ff180ca481555e2f3e8708c947cdc095/README.md?plain=1#L69

Just from the README it is unclear which is correct.

**Comment by Jayy001** [comment]
Hi, you are very much correct - appreciate you opening this, will correct it now.
